{% set name = "pyNSID" %}
{% set version = "0.0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37beeb6c0f57d2a0f5867849bd5f05bfba67c7c2589ab9579d7b222def456fe8

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
  run:
    - python >={{ python_min }}
    - cytoolz
    - dask-core >=0.10
    - h5py >=2.6.0
    - numpy >=1.10
    - sidpy >=0.0.2
    - six
    - toolz

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyNSID
    
about:
  home: https://github.com/pycroscopy/pyNSID
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Framework for storing, visualizing, and processing N-Dimensional Spectroscopic and Imaging Data (NSID)
  doc_url: https://pycroscopy.github.io/pyNSID/
  dev_url: https://github.com/pycroscopy/pyNSID

extra:
  recipe-maintainers:
    - gduscher
    - ssomnath
    - ramav87
